### ISSUE TITLE
Tests failing due to Symfony deprecation

### ISSUE THREAD

**Issue by legoktm** [wikimedia/composer-merge-plugin#33]
```
[km@km-tp composer-merge-plugin]$ composer test
PHP Fatal error:  Uncaught exception 'ErrorException' with message '"Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.' in /home/km/projects/composer-merge-plugin/vendor/symfony/console/Helper/DialogHelper.php:34
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(16384, '"Symfony\\Compon...', '/home/km/projec...', 34, Array)
#1 /home/km/projects/composer-merge-plugin/vendor/symfony/console/Helper/DialogHelper.php(34): trigger_error('"Symfony\\Compon...', 16384)
#2 /home/km/projects/composer-merge-plugin/vendor/composer/composer/src/Composer/Console/Application.php(331): Symfony\Component\Console\Helper\DialogHelper->__construct()
#3 /home/km/projects/composer-merge-plugin/vendor/symfony/console/Application.php(88): Composer\Console\Application->getDefaultHelperSet()
#4 /home/km/projects/composer-merge-plugin/vendor/composer/composer/src/Composer/Console/Application.php(70): Symfony\Compon in /home/km/projects/composer-merge-plugin/vendor/symfony/console/Helper/DialogHelper.php on line 34
```

**Comment by bd808** [comment]
Seems fixed now. See https://github.com/wikimedia/composer-merge-plugin/pull/36 for an example.
